#!/usr/bin/env python3
"""
Rigorous codebook analysis for the trained 256-code ProcessVAE.

For every active code, produces:
  - semantic_label: short human-readable name (derived from step text patterns)
  - category: one of [prep, heat-dry, heat-wet, mix, structure, finish, generic]
  - grammar_alignment: which 15-type grammar ops map to this code and at what %
  - top_examples: 5 representative step texts
  - frequency: how often this code is used across the sample

Output: data/models/process_vae/codebook_analysis.json
        data/figures/process_vae_codebook.png

Prerequisites:
Two files must exist before running this script:

  1. data/models/process_vae/codebook_labels_20k.json
     Generated by running process_vae_eval.py with a 20K recipe sample:
       python3 scripts/process_vae_eval.py --n_label_recipes 20000
     Then manually rename:
       mv data/models/process_vae/codebook_labels.json \
          data/models/process_vae/codebook_labels_20k.json

  2. data/models/process_vae/grammar_alignment.json
     Generated automatically by process_vae_eval.py (always created if
     constrained_dags_14b.jsonl exists).
"""

import argparse, json, re, sys
from pathlib import Path
from collections import defaultdict, Counter

import numpy as np
import matplotlib; matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches

BASE    = Path(__file__).resolve().parent.parent
VAE_DIR = BASE / "data/models/process_vae"

# ── Parse args early (module-level script, no main()) ─────────────────────────
_p = argparse.ArgumentParser()
_p.add_argument("--model_dir", type=str, default=None,
                help="Dir with codebook_labels_20k.json + grammar_alignment.json "
                     "(default: data/models/process_vae/)")
_p.add_argument("--out_dir",   type=str, default=None,
                help="Dir to save codebook_analysis.json + figure "
                     "(default: same as --model_dir)")
_args = _p.parse_args()

_model_dir = Path(_args.model_dir) if _args.model_dir else VAE_DIR
_out_dir   = Path(_args.out_dir)   if _args.out_dir   else _model_dir
_out_dir.mkdir(parents=True, exist_ok=True)

# ── Load data ──────────────────────────────────────────────────────────────────

_labels_path = _model_dir / "codebook_labels_20k.json"
_ga_path     = _model_dir / "grammar_alignment.json"

if not _labels_path.exists():
    raise FileNotFoundError(
        f"Missing: {_labels_path}\n"
        "Generate it by running:\n"
        f"  python3 scripts/process_vae_eval.py --n_label_recipes 20000 --out_dir {_model_dir}\n"
        "Then rename codebook_labels.json → codebook_labels_20k.json in that dir"
    )
if not _ga_path.exists():
    raise FileNotFoundError(
        f"Missing: {_ga_path}\n"
        "Generate it by running:\n"
        f"  python3 scripts/process_vae_eval.py --out_dir {_model_dir}\n"
        "(requires constrained_dags_14b.jsonl)"
    )

labels_20k = json.load(open(_labels_path))
ga         = json.load(open(_ga_path))

# ── Grammar reverse map: code → {gtype: pct} ──────────────────────────────────

code_grammar = defaultdict(dict)
for gtype, info in ga.items():
    for entry in info["top_codes"]:
        code_grammar[str(entry["code"])][gtype] = entry["pct"]

# ── Keyword patterns for auto-labeling ────────────────────────────────────────
# Order matters: first match wins. Checked against lowercased step text.

LABEL_RULES = [
    # Equipment prep
    ("preheat-oven",     r"preheat|heat oven|oven to \d"),
    ("preheat-grill",    r"preheat grill|heat grill|heat broiler"),
    ("prepare-pan",      r"grease|flour.*(pan|dish|tin)|spray.*(pan|dish)|butter.*(pan|dish)|line.*(pan|bak)"),
    ("prepare-vessel",   r"baking dish|baking pan|casserole|9.inch|8.inch|bundt|springform|muffin tin"),
    # Dry/wet heat
    ("bake-timed",       r"bake.*(minute|hour|until)|roast.*(minute|hour)"),
    ("bake-doneness",    r"toothpick|inserted.*center|comes out clean|golden brown|set.*oven"),
    ("broil",            r"broil|under.*broiler"),
    ("grill-cook",       r"grill.*minute|on.*grill|over.*coals|barbecue"),
    ("simmer",           r"simmer|low.*boil|gentle.*boil"),
    ("boil",             r"\bboil\b|bring.*to.*boil|boiling water|large pot.*water"),
    ("saute",            r"saut[eé]|skillet|frying pan|over medium|cook.*stirring"),
    ("steam",            r"\bsteam\b|steamer|steam.*basket"),
    ("microwave",        r"microwave|microwavable"),
    ("deep-fry",         r"deep.?fry|hot oil|375.*f|350.*f.*oil"),
    ("toast",            r"\btoast\b|toasted|toasting"),
    # Liquid/sauce ops
    ("reduce",           r"reduc|cook.*down|thicken|until.*syrupy"),
    ("deglaze",          r"deglaze|scrape.*brown|fond"),
    ("blanch",           r"blanch|ice water|cold water.*drain"),
    # Mixing
    ("whisk",            r"whisk|wire whisk"),
    ("beat",             r"\bbeat\b|electric mixer|stand mixer|medium speed|high speed"),
    ("fold",             r"\bfold\b|fold in|fold together|gently fold"),
    ("blend-processor",  r"food processor|blender|blend until smooth|process until"),
    ("knead",            r"\bknead\b|kneading"),
    ("stir",             r"\bstir\b|stir in|stir together|stir until"),
    ("combine-dry",      r"combine.*flour|sift|whisk.*flour|dry ingredient"),
    ("combine-wet",      r"combine.*egg|beat.*egg|whisk.*egg|mix.*egg"),
    ("mix-general",      r"\bmix\b|mix together|mix until|mixed"),
    # Structure / shaping
    ("roll-dough",       r"roll.*dough|roll out|rolling pin"),
    ("shape-dough",      r"shape|divide.*dough|form.*ball|flatten"),
    ("bread-machine",    r"bread machine|dough cycle|select.*cycle"),
    ("layer",            r"layer|arrange.*in|place.*over|spread.*over|top with"),
    ("pour",             r"\bpour\b|pour into|pour over|pour batter"),
    ("fill",             r"\bfill\b|spoon into|fill.*with"),
    # Prep / cutting
    ("chop-slice",       r"chop|dice|slice|mince|julienne|cut into"),
    ("season",           r"season with|salt and pepper|add salt|sprinkle.*salt"),
    ("marinate",         r"marinate|marinade|let.*rest.*minute|let.*sit.*minute"),
    # Finishing
    ("cool-rest",        r"cool|let.*cool|allow.*cool|rest|let.*rest|stand"),
    ("refrigerate",      r"refrigerat|chill|cold.*hour|overnight"),
    ("freeze",           r"freez|frozen"),
    ("serve",            r"\bserve\b|serving|serve with|place.*plate"),
    ("garnish",          r"garnish|top with|sprinkle.*top|drizzle.*over"),
    ("glaze-frost",      r"glaz|frost|icing|drizzle.*cake|pour.*over.*cake"),
    # Chocolate / confection
    ("melt-chocolate",   r"melt.*chocolate|chocolate.*melt|melt.*candy|candy coating"),
    ("ganache",          r"ganache|chocolate.*cream|cream.*chocolate|truffle"),
    # Misc
    ("store",            r"\bstore\b|keep.*refrigerat|keep.*freez|airtight"),
    ("yield-note",       r"yield|makes.*cup|serves|this recipe"),
    ("instruction-note", r"note:|tip:|important:|reminder:|\*\s"),
]

CATEGORY_MAP = {
    "preheat-oven": "prep", "preheat-grill": "prep",
    "prepare-pan": "prep", "prepare-vessel": "prep",
    "bake-timed": "heat-dry", "bake-doneness": "heat-dry",
    "broil": "heat-dry", "grill-cook": "heat-dry",
    "toast": "heat-dry", "deep-fry": "heat-dry",
    "simmer": "heat-wet", "boil": "heat-wet",
    "saute": "heat-wet", "steam": "heat-wet",
    "microwave": "heat-dry", "reduce": "heat-wet",
    "deglaze": "heat-wet", "blanch": "heat-wet",
    "whisk": "mix", "beat": "mix", "fold": "mix",
    "blend-processor": "mix", "knead": "mix",
    "stir": "mix", "combine-dry": "mix", "combine-wet": "mix",
    "mix-general": "mix",
    "roll-dough": "structure", "shape-dough": "structure",
    "bread-machine": "structure", "layer": "structure",
    "pour": "structure", "fill": "structure",
    "chop-slice": "prep", "season": "prep", "marinate": "prep",
    "cool-rest": "finish", "refrigerate": "finish", "freeze": "finish",
    "serve": "finish", "garnish": "finish", "glaze-frost": "finish",
    "melt-chocolate": "heat-dry", "ganache": "finish",
    "store": "finish", "yield-note": "meta", "instruction-note": "meta",
}

CATEGORY_COLORS = {
    "prep":     "#4C72B0",
    "heat-dry": "#C44E52",
    "heat-wet": "#DD8452",
    "mix":      "#55A868",
    "structure":"#8172B2",
    "finish":   "#64B5CD",
    "meta":     "#AAAAAA",
    "unknown":  "#DDDDDD",
}

def auto_label(texts):
    """Return (label, category, match_count) for a code given its example steps."""
    vote = Counter()
    for txt in texts:
        t = txt.lower()
        for label, pat in LABEL_RULES:
            if re.search(pat, t):
                vote[label] += 1
                break
    if not vote:
        return "unknown", "unknown", 0
    best_label, count = vote.most_common(1)[0]
    cat = CATEGORY_MAP.get(best_label, "unknown")
    return best_label, cat, count


# ── Per-code analysis ──────────────────────────────────────────────────────────

analysis = {}
for code_str, texts in labels_20k.items():
    c = int(code_str)
    label, cat, match_count = auto_label(texts)
    gram = code_grammar.get(code_str, {})
    top_gram = sorted(gram.items(), key=lambda x: -x[1])[:2]

    analysis[c] = {
        "code":            c,
        "semantic_label":  label,
        "category":        cat,
        "label_confidence": round(match_count / len(texts), 2) if texts else 0,
        "grammar_alignment": {g: round(p, 3) for g, p in top_gram},
        "frequency":       len(texts),
        "top_examples":    [t[:100] for t in texts[:5]],
    }

# ── Summary stats ──────────────────────────────────────────────────────────────

total = len(analysis)
by_cat = Counter(v["category"] for v in analysis.values())
by_label = Counter(v["semantic_label"] for v in analysis.values())

print(f"\n{'='*60}")
print(f"CODEBOOK ANALYSIS — {total} active codes / 256 total")
print(f"{'='*60}\n")

print("By category:")
for cat, n in sorted(by_cat.items(), key=lambda x: -x[1]):
    bar = "█" * n
    print(f"  {cat:12s}  {n:3d}  {bar}")

print("\nTop semantic labels:")
for label, n in by_label.most_common(20):
    print(f"  {label:25s}  {n:3d} codes")

print("\nPer-category code breakdown:")
by_cat_codes = defaultdict(list)
for c, info in sorted(analysis.items()):
    by_cat_codes[info["category"]].append(info)

for cat in ["prep","heat-dry","heat-wet","mix","structure","finish","meta","unknown"]:
    codes = by_cat_codes[cat]
    if not codes: continue
    print(f"\n── {cat.upper()} ({len(codes)} codes) ──")
    for info in sorted(codes, key=lambda x: -x["frequency"])[:8]:
        gram_str = ", ".join(f'{g}({p:.0%})' for g,p in info["grammar_alignment"].items()) or "—"
        ex = info["top_examples"][0][:70] if info["top_examples"] else "—"
        print(f"  c{info['code']:03d}  [{info['semantic_label']:<20s}]  gram={gram_str}")
        print(f"       \"{ex}\"")

# ── Save ──────────────────────────────────────────────────────────────────────

json.dump(
    {str(c): v for c, v in sorted(analysis.items())},
    open(_out_dir / "codebook_analysis.json", "w"),
    indent=2
)
print(f"\nSaved → {_out_dir}/codebook_analysis.json")

# ── Figure: codebook map by category ─────────────────────────────────────────

fig, axes = plt.subplots(1, 2, figsize=(16, 6))
fig.suptitle("Process VAE — Codebook Analysis (234 active codes)", fontsize=13, fontweight="bold")

# Left: category distribution
ax = axes[0]
cats   = [c for c, _ in sorted(by_cat.items(), key=lambda x: -x[1])]
counts = [by_cat[c] for c in cats]
colors = [CATEGORY_COLORS.get(c, "#DDD") for c in cats]
bars   = ax.barh(cats, counts, color=colors, alpha=0.85)
for bar, v in zip(bars, counts):
    ax.text(v + 0.3, bar.get_y() + bar.get_height()/2,
            str(v), va="center", fontsize=9)
ax.set_xlabel("# codes")
ax.set_title("Codes by functional category\n(auto-labeled from step text)")
ax.set_xlim(0, max(counts) * 1.15)

# Right: 16×16 grid of all 256 codes colored by category
ax = axes[1]
grid = np.zeros((16, 16, 3))
for i in range(256):
    row, col = i // 16, i % 16
    info = analysis.get(i)
    if info:
        cat = info["category"]
        hex_c = CATEGORY_COLORS.get(cat, "#DDD").lstrip("#")
        r, g, b = tuple(int(hex_c[j:j+2], 16)/255 for j in (0,2,4))
        grid[row, col] = [r, g, b]
    else:
        grid[row, col] = [0.9, 0.9, 0.9]  # dead code = light gray

ax.imshow(grid, aspect="equal")
ax.set_xticks([]); ax.set_yticks([])
ax.set_title("256-code grid (row-major order)\ngray = dead code")

# annotate a few landmark codes
landmarks = {
    240: "preheat\noven",
    34:  "preheat\ngrill",
    80:  "knead",
    239: "blend",
    133: "boil",
    19:  "simmer",
}
for c, lbl in landmarks.items():
    row, col = c // 16, c % 16
    ax.text(col, row, lbl, ha="center", va="center",
            fontsize=5.5, color="white", fontweight="bold",
            bbox=dict(boxstyle="round,pad=0.1", fc="black", alpha=0.5, lw=0))

legend_patches = [mpatches.Patch(color=v, label=k) for k, v in CATEGORY_COLORS.items()]
ax.legend(handles=legend_patches, loc="lower right", fontsize=7,
          framealpha=0.9, ncol=2)

plt.tight_layout()
fig.savefig(BASE / "data/figures/process_vae_codebook.png", dpi=130)
plt.close()
print(f"Figure → data/figures/process_vae_codebook.png")
